before_install:
  - git clone https://git.cryptomilk.org/projects/cmocka.git
  - cd cmocka
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..

script:
  - gcc -DTEST_BUILD -o emuciaa/hal/ciaa_tests_dht11 emuciaa/hal/test/check_sapi_dht11.c emuciaa/hal/sapi/external_peripherals/temperature_humudity/dht11/src/sapi_dht11.c emuciaa/hal/test/mock/dht11_api_mock.c emuciaa/hal/test/mock/sapi_delay_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/external_peripherals/temperature_humudity/dht11/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_tests_dht11
  - gcc -DTEST_BUILD -o emuciaa/hal/ciaa_tests_gpio emuciaa/hal/test/check_sapi_gpio.c emuciaa/hal/sapi/soc/peripherals/src/sapi_gpio.c emuciaa/hal/test/mock/gpio_api_mock.c emuciaa/hal/test/mock/sapi_interrupt_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_tests_gpio
  - gcc -DTEST_BUILD -o emuciaa/hal/ciaa_tests_rtc emuciaa/hal/test/check_sapi_rtc.c emuciaa/hal/sapi/soc/peripherals/src/sapi_rtc.c emuciaa/hal/test/mock/rtc_api_mock.c emuciaa/hal/test/mock/sapi_delay_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_tests_rtc
  - gcc -DTEST_BUILD -o emuciaa/hal/ciaa_tests_delay emuciaa/hal/test/check_sapi_delay.c emuciaa/hal/sapi/soc/peripherals/src/sapi_delay.c emuciaa/hal/test/mock/delay_api_mock.c emuciaa/hal/test/mock/sapi_tick_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_tests_delay  
  - gcc -DTEST_BUILD -include /dev/null -o emuciaa/hal/ciaa_tests_tick emuciaa/hal/test/check_sapi_tick.c emuciaa/hal/sapi/soc/peripherals/src/sapi_tick.c emuciaa/hal/test/mock/tick_api_mock.c emuciaa/hal/test/mock/sapi_uart_mock.c emuciaa/hal/test/mock/equeue_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_tests_tick
  - gcc -DTEST_BUILD -o emuciaa/hal/ciaa_tests_tasks emuciaa/hal/test/check_tasks_api.c emuciaa/hal/test/mock/tasks_api_mock.c -Iemuciaa/hal/sapi/base  -Iemuciaa/hal/sapi/board  -I./emuciaa/hal/test/mock -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_tests_tasks
  - gcc -DTEST_BUILD  -o emuciaa/hal/ciaa_test_integration_delay_tick emuciaa/hal/test/check_test_integration_delay_tick.c emuciaa/hal/sapi/soc/peripherals/src/sapi_delay.c emuciaa/hal/test/mock/delay_api_mock.c emuciaa/hal/test/mock/sapi_tick_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_test_integration_delay_tick
  - gcc -DTEST_BUILD  -o emuciaa/hal/ciaa_test_integration_gpio_interrupt emuciaa/hal/test/check_test_integration_gpio_interrupt.c emuciaa/hal/sapi/soc/peripherals/src/sapi_gpio.c emuciaa/hal/test/mock/gpio_api_mock.c emuciaa/hal/test/mock/sapi_interrupt_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_test_integration_gpio_interrupt
  - gcc -DTEST_BUILD  -o emuciaa/hal/ciaa_test_integration_rtc_delay emuciaa/hal/test/check_test_integration_rtc_delay.c emuciaa/hal/sapi/soc/peripherals/src/sapi_rtc.c emuciaa/hal/test/mock/rtc_api_mock.c emuciaa/hal/test/mock/sapi_delay_mock.c -I. -I./emuciaa/hal/sapi -I./emuciaa/hal/test/mock -Iemuciaa/hal/sapi/base -Iemuciaa/hal/sapi/board  -Iemuciaa/hal/sapi/soc/peripherals/inc -lcheck -lcmocka -lrt -pthread -lm -lsubunit
  - ./emuciaa/hal/ciaa_test_integration_rtc_delay

before_script:
  - sudo apt-get update
  - sudo apt-get install -y check

after_script:
  - echo "Pruebas unitarias completadas."
  - echo "Pruebas de integracion completadas."

after_success:
  - echo "Pruebas unitarias completadas con exito."
  - echo "Pruebas de integracion completadas con exito."

after_failure:
  - echo "Pruebas unitarias completadas con errores."
  - echo "Pruebas de integracion completadas con errores."
